apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "recipe-api.fullname" . }}
  labels:
    {{- include "recipe-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "recipe-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "recipe-api.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: recipe-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
              name: http
          envFrom:
            - configMapRef:
                name: {{ include "recipe-api.fullname" . }}-config
            - secretRef:
                name: {{ include "recipe-api.fullname" . }}-db
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
