apiVersion: v1
kind: Secret
metadata:
  name: {{ include "recipe-api.fullname" . }}-db
  labels:
    {{- include "recipe-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: {{ required "database.connectionString is required" .Values.database.connectionString | quote }}
